#!/bin/sh

ADDR="targetprocess.com"
BRANCH=$(git symbolic-ref --short HEAD)
# credentials format USER@HOST:PASSWORD
CREDENTIALS=$(cat ~/credentials)

if [[ ! $BRANCH =~ ^[[:digit:]]+$ ]];
then
  exit 0
fi

check_jq() {
    type jq $2>1 $1>/dev/null
    if [ $? != 0 ]
    then
        echo 'jq JSON parser not found!'
        exit 1
    fi
}

check_jq

USER_STORY_ID=$BRANCH;
ENTITY_PATH="$ADDR/api/v1/UserStories/$USER_STORY_ID?include=\[Name\]";
TITLE=`curl $ENTITY_PATH -H 'Accept: application/json' --user $CREDENTIALS -s | jq '.Name' --raw-output`;
TEMPLATE=$(cat $1)
echo "$BRANCH $TITLE\n$TEMPLATE">$1
